// Generate API/storage reference from checked contracts and source declarations.
import { readFile, writeFile } from 'node:fs/promises'
import { parse } from 'yaml'

const api = parse(await readFile('docs/api.openapi.yml', 'utf8'))
const types = await readFile('src/db/types.ts', 'utf8')
const database = await readFile('src/db/db.ts', 'utf8')
const lines = [
  '# Generated contract reference',
  '',
  'Generated by `npm run docs:generate`. Do not edit by hand.',
  '',
  '## HTTP endpoints',
  '',
]
for (const [path, methods] of Object.entries(api.paths)) {
  for (const [method, detail] of Object.entries(methods)) {
    lines.push(`- \`${method.toUpperCase()} ${path}\`: ${detail.summary}.`)
  }
}
lines.push('', '## IndexedDB record types', '')
for (const [, name] of types.matchAll(/export interface (\w+)/g)) lines.push(`- \`${name}\``)
const versions = [...new Set([...database.matchAll(/this\.version\((\d+)\)/g)].map((m) => m[1]))]
versions.sort((a, b) => Number(a) - Number(b))
lines.push('', `Dexie migration versions: ${versions.join(', ')}.`)
const content = lines.join('\n') + '\n'
const target = 'docs/generated-contracts.md'
if (process.argv.includes('--check')) {
  if ((await readFile(target, 'utf8')) !== content) {
    throw new Error('Generated docs stale; run npm run docs:generate')
  }
  console.log('Generated contract documentation is current')
} else {
  await writeFile(target, content)
  console.log(`Generated ${target}`)
}
