"""Generate API/storage reference from checked contracts and source declarations."""
import json
import re
import sys
from pathlib import Path

import yaml

root = Path(__file__).resolve().parents[1]
api = yaml.safe_load((root / 'docs/api.openapi.yml').read_text())
types = (root / 'src/db/types.ts').read_text()
database = (root / 'src/db/db.ts').read_text()
sync = json.loads((root / 'docs/sync.schema.json').read_text())
lines = [
    '# Generated contract reference',
    '',
    'Generated by `npm run docs:generate`. Do not edit by hand.',
    '',
    '## HTTP endpoints',
    '',
]
for path, methods in api['paths'].items():
    for method, detail in methods.items():
        lines.append(f'- `{method.upper()} {path}`: {detail["summary"]}.')
lines += ['', '## IndexedDB record types', '']
for name in re.findall(r'export interface (\w+)', types):
    lines.append(f'- `{name}`')
versions = sorted(set(re.findall(r'this\.version\((\d+)\)', database)), key=int)
lines += ['', f'Dexie migration versions: {", ".join(versions)}.', '', '## Narrator artifact', '']
lines.append(f'Required top-level fields: {", ".join(sync["required"])}.')
content = '\n'.join(lines) + '\n'
target = root / 'docs/generated-contracts.md'
if '--check' in sys.argv:
    assert target.read_text() == content, 'Generated docs stale; run npm run docs:generate'
    print('Generated contract documentation is current')
else:
    target.write_text(content)
    print('Generated docs/generated-contracts.md')
